DROP DATABASE IF EXISTS Personal;

CREATE DATABASE Personal;

USE Personal;

CREATE TABLE Area
(
	IdArea INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50)
);

CREATE TABLE Zona
(
	IdZona INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50)
);

CREATE TABLE Puesto
(
	IdPuesto INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(50)
);

CREATE TABLE Alumnos
(
	Nombre VARCHAR(100) NOT NULL,
	Login INT NOT NULL,
    Area INT NOT NULL,
    Zona INT NOT NULL,
    Puesto INT,
    CONSTRAINT FK_AZona
    FOREIGN KEY (Area) REFERENCES Personal.Area(IdArea) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_ZZona
    FOREIGN KEY (Zona) REFERENCES Personal.Zona(IdZona) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT FK_APuesto
    FOREIGN KEY (Puesto) REFERENCES Personal.Puesto(IdPuesto) ON UPDATE NO ACTION ON DELETE NO ACTION,
    UNIQUE (LOGIN)
);